# Generated by Django 4.1.5 on 2023-01-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('other_names', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('nis', models.IntegerField()),
                ('paye', models.IntegerField()),
            ],
        ),
    ]
