# Generated by Django 4.1.5 on 2023-01-11 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0006_publications_awards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awards',
            options={'ordering': ['-created'], 'verbose_name': 'Award', 'verbose_name_plural': 'Awards'},
        ),
        migrations.AlterModelOptions(
            name='publications',
            options={'ordering': ['-created'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AddField(
            model_name='awards',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awards',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publications',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publications',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
