# Generated by Django 4.1.5 on 2023-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0008_remove_employee_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Employee ID Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type'),
        ),
    ]
