# Generated by Django 4.1.5 on 2023-01-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0009_employee_employeeid_employee_employeetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeid',
        ),
    ]
