# Generated by Django 4.1.5 on 2023-01-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0011_alter_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
    ]
