# Generated by Django 4.1.5 on 2023-01-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0012_alter_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Bio'),
        ),
    ]
