# Generated by Django 4.1.5 on 2023-01-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0014_alter_employee_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ssnitnumber',
        ),
        migrations.AddField(
            model_name='employee',
            name='nisnumber',
            field=models.IntegerField(blank=True, max_length=9, null=True, verbose_name='NIS Number'),
        ),
    ]
