# Generated by Django 4.1.5 on 2023-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0016_alter_employee_nisnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nisnumber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='NIS Number'),
        ),
    ]
