# Generated by Django 4.1.5 on 2023-01-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0018_alter_publications_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vitae',
            field=models.FileField(blank=True, help_text='upload in .docx or .pdf', null=True, upload_to='', verbose_name='Cirriculum Vitae'),
        ),
    ]
