# Generated by Django 4.1.5 on 2023-02-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0019_employee_vitae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
