# Generated by Django 4.1.5 on 2023-02-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0021_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='vitae',
            field=models.FileField(blank=True, help_text='upload in .docx or .pdf', null=True, upload_to='vitae', verbose_name='Cirriculum Vitae'),
        ),
    ]
