# Generated by Django 4.1.5 on 2023-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0026_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], default='Not Known', max_length=10, verbose_name='Gender'),
        ),
    ]
