# Generated by Django 4.1.5 on 2023-03-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0027_alter_employee_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default='0000-00-00', null=True, verbose_name='Date of Birth'),
        ),
    ]
