# Generated by Django 4.1.5 on 2023-03-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0028_alter_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
