# Generated by Django 4.1.5 on 2023-03-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0029_alter_employee_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tinnumber',
        ),
    ]
