# Generated by Django 4.1.5 on 2023-03-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0031_presentations_manuscripts_development_consultancies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancies',
            name='period',
            field=models.CharField(max_length=20, null=True, verbose_name='Period'),
        ),
    ]
