# Generated by Django 4.1.5 on 2023-03-17 04:01

import django.core.validators
from django.db import migrations, models
import staff_app.validate


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0032_alter_consultancies_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentations',
            name='period',
        ),
        migrations.AddField(
            model_name='presentations',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), staff_app.validate.max_value_current_year], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='awards',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), staff_app.validate.max_value_current_year], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), staff_app.validate.max_value_current_year], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), staff_app.validate.max_value_current_year], verbose_name='Year'),
        ),
    ]
