# Generated by Django 4.1.5 on 2023-03-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0033_remove_presentations_period_presentations_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancies',
            name='period',
        ),
        migrations.RemoveField(
            model_name='development',
            name='period',
        ),
        migrations.AddField(
            model_name='consultancies',
            name='year_end',
            field=models.IntegerField(null=True, verbose_name='End Year'),
        ),
        migrations.AddField(
            model_name='consultancies',
            name='year_start',
            field=models.IntegerField(null=True, verbose_name='Start Year'),
        ),
        migrations.AddField(
            model_name='development',
            name='year_end',
            field=models.IntegerField(null=True, verbose_name='End Year'),
        ),
        migrations.AddField(
            model_name='development',
            name='year_start',
            field=models.IntegerField(null=True, verbose_name='Start Year'),
        ),
    ]
