# Generated by Django 4.1.5 on 2023-03-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0041_alter_publications_publicationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='year',
            field=models.CharField(max_length=9, null=True, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='conferences',
            name='year',
            field=models.CharField(max_length=9, null=True, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='presentations',
            name='year',
            field=models.CharField(max_length=9, null=True, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='year',
            field=models.CharField(max_length=9, null=True, verbose_name='Academic Year'),
        ),
    ]
