# Generated by Django 4.1.5 on 2023-03-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0042_alter_awards_year_alter_conferences_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='stafff_id',
        ),
        migrations.DeleteModel(
            name='LeaveReport',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
