# Generated by Django 4.1.5 on 2023-03-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0044_supervision_specialistion_roles_research'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
