# Generated by Django 4.1.5 on 2023-03-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0046_rename_specialistion_specialisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialisation',
            options={'ordering': ['-created'], 'verbose_name': 'Specialisation', 'verbose_name_plural': 'Specialisation'},
        ),
    ]
