# Generated by Django 4.1.5 on 2023-03-23 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_app', '0048_alter_employee_vitae'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(choices=[('Study and Travel Grant', 'Study and Travel Grant'), ('Institutional Visit Allowance', 'Institutional Visit Allowance'), ('Development and Training Grant', 'Development and Training Grant'), ('Book Grant', 'Book Grant'), ('Claim Form', 'Claim Form'), ('Pension Plans', 'Pension Plans')], default='Study and Travel Grant', max_length=40, verbose_name='Information')),
                ('message', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['-created'],
            },
        ),
    ]
