# Generated by Django 4.1.5 on 2023-03-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0049_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emergency',
        ),
    ]
