# Generated by Django 4.1.5 on 2023-03-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0051_requests_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Employee ID'),
        ),
    ]
