# Generated by Django 4.1.5 on 2023-03-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0053_honours_contributions_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscripts',
            name='in_preparation',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='in_review',
        ),
        migrations.AddField(
            model_name='manuscripts',
            name='status',
            field=models.CharField(choices=[('in preparation', 'in preparation'), ('under review', 'in review')], default='in preparation', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
