# Generated by Django 4.1.5 on 2023-03-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0055_alter_manuscripts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervision',
            name='firstname',
            field=models.CharField(max_length=125, verbose_name='Student First name'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='lastname',
            field=models.CharField(max_length=125, verbose_name='Student Last name'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True, verbose_name='Student Degree Level'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Project/Thesis Title'),
        ),
    ]
