# Generated by Django 4.1.5 on 2023-03-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0057_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='status',
        ),
    ]
