# Generated by Django 4.1.5 on 2023-03-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0059_alter_requests_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
