# Generated by Django 4.1.5 on 2023-01-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0003_rename_username_logininfo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
    ]
