# Generated by Django 4.1.5 on 2023-01-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0004_delete_logininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='address',
        ),
        migrations.AddField(
            model_name='staffuser',
            name='profile_pic',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
