# Generated by Django 4.1.5 on 2023-01-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0006_alter_staffuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='profile_pic',
        ),
    ]
