# Generated by Django 4.1.5 on 2023-01-09 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0007_remove_staffuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='profile_pic',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
