# Generated by Django 4.1.5 on 2023-03-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris_app', '0008_staffuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='profile_pic',
        ),
    ]
